name: Python Trie CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v1
      with:
        activate-environment: micendemons
        auto-update-conda: true
        auto-activate-base: false
        python-version: ${{ matrix.python-version }}
        environment-file: Languages/Python/nice_implementations/env.yml
    - name: Conda info
      shell: bash -l {0}
      run: conda info
    - name: Conda list
      shell: pwsh
      run: conda list
    - name: Test with pytest
      shell: bash -l {0}
      run: |
        coverage run -m pytest Languages/Python
        coverage report --fail-under=100
